plugins:
  - jest

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

env:
  node: true
  jest: true

parser: babel-eslint

rules:
  no-console: 0
  no-debugger: 0
  object-curly-newline: 0
  jest/no-disabled-tests: 0